config/routes.rb
Rails.application.routes.draw do
  root to: redirect('activities')

  devise_for :employees, controllers: {
    sessions: 'employees/sessions'
  }

  resources :customers
  resources :customer_groups
  resources :activity_categories do
    resources :text_templates
  end
  resources :activities do
    collection do
      scope module: :activities, as: :activities do
        resources :suggestions, only: [:index]
        resources :reports, only: [:new, :create]
      end
    end
  end
  resources :op_lists, only: [:new, :create]

  resources :expenses
  resources :absences do
    get :default_hours, on: :collection
  end
  resources :employees do
    resources :hourly_rates
  end

  resources :target_hours, only: [:index]
  resource :target_hours, only: [:update]

  resources :hours, only: [:index] do
    collection do
      scope module: :hours, as: :hours do
        resources :subjects, only: [:index]
        resources :calendar_events, only: [:index]
      end
    end
  end

  resources :invoices, except: :edit do
    member do
      patch :deliver
      patch :charge
      patch :reopen
    end

    scope module: :invoices do
      resources :activities, except: [:new, :index] do
        get :templates
        patch :reorder
        patch :toggle_pagebreak
        patch :ungroup
        patch :group, on: :collection
        post :generate, on: :collection
      end

      collection do
        namespace :activities do
          resources :suggestions, only: [:index]
        end
      end

      resources :expenses, except: [:new, :index] do
        patch :reorder
        patch :ungroup
        patch :group, on: :collection
        post :generate, on: :collection
      end

      resources :payments
      resource :delivery, only: [:new, :update]
      resource :mail, only: [:new, :create, :show]
      resource :pdf, only: [:new, :show] do
        get :qr_bill
      end

      controller '/invoices/wizard' do
        patch :wizard, action: :update

        namespace :wizard do
          get :customer
          get :activities
          get :expenses
          get :complete
          get :summary

          patch :finish
        end
      end
    end
  end

  resources :debtors_reports, only: [:new, :create]
  resources :versions, only: [:index]
  resources :settings, only: [:index, :update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/employee.rb
require 'bcrypt'

class Employee < ApplicationRecord
  devise :database_authenticatable, :rememberable

  extend Enumerize

  has_many :hourly_rates, dependent: :destroy

  scope :for_query, lambda { |query|
    return if query.blank?

    where('lower(name) LIKE lower(?)', "%#{query}%")
  }

  scope :active, -> { where(deactivated: false) }

  validates :initials, :hourly_rate, :worktime_model, presence: true
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8 }, unless: -> { persisted? && password.nil? }, confirmation: true
  validates :password_confirmation, presence: true, unless: -> { persisted? && password.nil? }
  validate :check_deactivate
  validates :workload, presence: true,
                       numericality: { greater_than: 0, less_than_or_equal_to: 100 },
                       unless: lambda {
                         worktime_model.debit_is_actual?
                       }

  enumerize :worktime_model, in: { target_hours: 0, debit_is_actual: 1 }, default: :target_hours

  monetize :hourly_rate_cents

  def activity_hours_today
    Activity.for_employee(self).where(date: Date.current).sum(:hours)
  end

  def target_hours_reached_in_percent
    activity_hours = activity_hours_today
    target_hours = TargetHours.hours_between(from: Date.current, to: Date.current)

    activity_hours >= target_hours ? 100 : (100.0 / target_hours * activity_hours)
  end

  def check_deactivate
    return unless deactivated

    if Effort.for_employee(self).for_state(:open).count.positive?
      errors.add :deactivated, :open_efforts_error
    elsif Invoice.for_employee(self).where.not(state: :charged).count.positive?
      errors.add :deactivated, :open_invoices_error
    end
  end

  # this method is called by devise to check for "active" state of the model
  def active_for_authentication?
    !deactivated?
  end

  # always remember for devise
  def remember_me
    true
  end

  def workload_in_percent
    workload * 0.01
  end
end

app/controllers/employees/sessions_controller.rb
module Employees
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    layout 'login'

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  responders :flash

  def index
    @employees = @employees.active unless params[:deactivated]
    @employees = @employees.for_query(params[:query])
    @employees = @employees.order(:name)
  end

  def create
    @employee.save
    respond_with @employee, location: employees_path
  end

  def update
    @employee.update employee_params
    respond_with @employee, location: employees_path
  end

  def destroy
    @employee.destroy
    respond_with @employee
  end

  private

  def employee_params
    employee_params = params.require(:employee).permit :name,
                                                       :email,
                                                       :initials,
                                                       :hourly_rate,
                                                       :worktime_model,
                                                       :workload,
                                                       :password,
                                                       :password_confirmation,
                                                       :deactivated

    employee_params.delete :password if employee_params[:password].blank?

    employee_params
  end
end

app/views/employees/_employee.html.erb
<div class="row">
  <div class="col-md-8"><%= employee.name %></div>
  <div class="col-md-4">
     <%= link_to t('resources.edit', resource: Employee.model_name.human), edit_employee_path(employee), class: 'btn btn-default' %> 
  </div>
</div>

app/views/employees/_form.html.erb
<%= simple_form_for @employee do |f| %>
  <fieldset>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :initials %>
    <%= f.input :hourly_rate %>
    <%= f.input :worktime_model, include_blank: false %>
    <%= f.input :workload %>
    <%= f.input :password, type: :password %>
    <%= f.input :password_confirmation, type: :password %>
    <%= f.input :deactivated %>
  </fieldset>

  <%= render 'shared/default_form_actions', f: f, entity: @employee %>
<% end %>

app/views/employees/edit.html.erb
<%= page_title_for resource: Employee, action: :edit %>

<%= render 'form' %>

app/views/employees/index.html.erb
<%= page_title_for resource: Employee, action: :index %>

<div class="table-row">
  <table class="management">
    <thead>
      <th class="name"><%= Employee.human_attribute_name :name %></th>
      <th class="initials"><%= Employee.human_attribute_name :initials %></th>
      <% if params[:deactivated] %>
        <th class="deactivated"><%= Employee.human_attribute_name :deactivated %></th>
      <% end %>
      <th class="actions"></th>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.initials %></td>
          <% if params[:deactivated] %>
            <td class="deactivated"><%= fa_icon :times if employee.deactivated? %></td>
          <% end %>
          <td><%= link_to_edit employee %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="actions">
  <% if can? :create, Employee %>
    <%= button_to_new Employee %>
  <% end %>

  <% if params[:deactivated] %>
    <%= link_to t('.exclude_deactivated'), employees_path %>
  <% else %>
    <%= link_to t('.include_deactivated'), employees_path(deactivated: true) %>
  <% end %>
</div>

app/views/employees/new.html.erb
<%= page_title_for resource: Employee, action: :new %>

<%= render 'form' %>