config/routes.rb
Rails.application.routes.draw do
  root to: redirect('activities')

  devise_for :employees, controllers: {
    sessions: 'employees/sessions'
  }

  resources :customers
  resources :customer_groups
  resources :activity_categories do
    resources :text_templates
  end
  resources :activities do
    collection do
      scope module: :activities, as: :activities do
        resources :suggestions, only: [:index]
        resources :reports, only: [:new, :create]
      end
    end
  end
  resources :op_lists, only: [:new, :create]

  resources :expenses
  resources :absences do
    get :default_hours, on: :collection
  end
  resources :employees do
    resources :hourly_rates
  end

  resources :target_hours, only: [:index]
  resource :target_hours, only: [:update]

  resources :hours, only: [:index] do
    collection do
      scope module: :hours, as: :hours do
        resources :subjects, only: [:index]
        resources :calendar_events, only: [:index]
      end
    end
  end

  resources :invoices, except: :edit do
    member do
      patch :deliver
      patch :charge
      patch :reopen
    end

    scope module: :invoices do
      resources :activities, except: [:new, :index] do
        get :templates
        patch :reorder
        patch :toggle_pagebreak
        patch :ungroup
        patch :group, on: :collection
        post :generate, on: :collection
      end

      collection do
        namespace :activities do
          resources :suggestions, only: [:index]
        end
      end

      resources :expenses, except: [:new, :index] do
        patch :reorder
        patch :ungroup
        patch :group, on: :collection
        post :generate, on: :collection
      end

      resources :payments
      resource :delivery, only: [:new, :update]
      resource :mail, only: [:new, :create, :show]
      resource :pdf, only: [:new, :show] do
        get :qr_bill
      end

      controller '/invoices/wizard' do
        patch :wizard, action: :update

        namespace :wizard do
          get :customer
          get :activities
          get :expenses
          get :complete
          get :summary

          patch :finish
        end
      end
    end
  end

  resources :debtors_reports, only: [:new, :create]
  resources :versions, only: [:index]
  resources :settings, only: [:index, :update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/invoices/expenses/generate.rb
module Invoices
  module Expenses
    class Generate < Invoices::Efforts::Generate
      def initialize(invoice, generate_default_expense: false)
        super(invoice)

        @generate_default_expense = generate_default_expense
      end

      def generate!
        super

        return unless @generate_default_expense

        Invoices::Expense.create_default_expense_for @invoice
      end

      def efforts_class
        ::Expense
      end

      def invoice_efforts_class
        Invoices::Expense
      end
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  include EntitiesFilterable

  load_and_authorize_resource
  responders :flash

  def index
    @expenses = @expenses.order(date: :desc)
    @expenses = @filter.filter @expenses
    @expenses = @expenses.includes(:employee, :customer, :invoice_effort)
    @total_amount = Money.new @expenses.sum(:amount_cents)
    @expenses = @expenses.paginate(page: params[:page])
  end

  def new
    @expense.employee = current_employee
    @expense.date = Time.zone.today
  end

  def create
    @expense.save
    respond_with @expense, location: expenses_path
  end

  def update
    @expense.update expense_params
    respond_with @expense, location: expenses_path
  end

  def destroy
    @expense.destroy
    respond_with @expense
  end

  private

  def expense_params
    params.require(:expense).permit :name, :employee_id, :customer_id, :text, :date, :note, :amount
  end
end

app/controllers/invoices/expenses_controller.rb
module Invoices
  class ExpensesController < EffortsController
    load_and_authorize_resource :invoice
    load_and_authorize_resource through: :invoice

    respond_to :html

    def create
      @expense.save
      redirect_to invoice_wizard_expenses_path(@invoice)
    end

    def update
      respond_to do |format|
        if @expense.update expense_params
          format.html { redirect_to invoice_wizard_expenses_path(@invoice) }
          format.json { head :no_content }
        else
          format.html { render action: 'index' }
          format.json { render json: @expense.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @expense.destroy
      redirect_to invoice_wizard_expenses_path(@invoice)
    end

    def generate
      Invoices::Expenses::Generate.new(@invoice).generate!
      redirect_to invoice_wizard_expenses_path(@invoice)
    end

    def effort
      @expense
    end

    def effort_params
      expense_params
    end

    def invoice_wizard_path
      invoice_wizard_expenses_path(@invoice)
    end

    private

    def expense_params
      params.require(:expense).permit :invoice_id,
                                      :text,
                                      :amount_manually,
                                      :visible,
                                      :position,
                                      effort_ids: []
    end
  end
end

app/views/expenses/_expense.html.erb
<div class="row">
  <div class="col-md-4"><%= expense.text %></div>
  <div class="col-md-4"><%= expense.amount %></div>
  <div class="col-md-4">
    <%= link_to t('resources.edit', resource: Expense.model_name.human),
      edit_expense_path(expense), class: 'btn btn-default' %>
  </div>
</div>

app/views/expenses/_filter_row.html.erb
<div class="filter">
  <%= simple_form_for @filter, url: expenses_path, method: :get, as: :filter do |form| %>
    <%= render 'filters/default_row', form: form %>

    <div class="filter-row">
      <%= render 'filters/state_column', form: form, collection: Expense.state.options %>

      <%= render 'filters/customer_group_column', form: form %>
    </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<%= simple_form_for @expense do |f| %>
  <fieldset>
    <%= f.association :employee, as: :hidden %>
    <%= f.association :customer, input_html: { class: 'customer_select' } %>
    <%= f.input :date, as: :date_picker %>
    <%= f.input :amount %>
    <%= f.input :text %>
    <%= f.input :note %>
  </fieldset>

  <%= render 'shared/default_form_actions', f: f, entity: @expense %>
<% end %>

app/views/expenses/edit.html.erb
<%= page_title_for resource: Employee, action: :edit %>

<%= render 'form' %>

app/views/expenses/index.html.erb
<%= page_title_for resource: Expense, action: :index %>

<%= render 'filter_row' %>

<div class="table-row">
  <% if @expenses.any? %>
    <table class="management">
      <thead>
        <th class="employee"><%= Expense.human_attribute_name(:employee) %></th>
        <th class="customer"><%= Expense.human_attribute_name(:customer) %></th>
        <th class="date"><%= Expense.human_attribute_name(:date) %></th>
        <th class="amount"><%= Expense.human_attribute_name(:amount) %></th>
        <th class="text"><%= Expense.human_attribute_name(:text) %></th>
        <th class="note"></th>
        <th class="actions"></th>
      </thead>

      <tbody>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.employee.name %></td>
            <td><%= present(expense.customer) { |customer| customer.display_name } %></td>
            <td><%= l expense.date %></td>
            <td class="amount"><%= humanized_money expense.amount %></td>
            <td class="text"><%= expense.text %></td>
            <td class="note">
              <%= tooltip_icon_for(expense.note, title: Expense.human_attribute_name(:note)) if expense.note.present? %>
            </td>
            <td>
              <% if expense.invoice.present? %>
                <%= link_to Invoice.model_name.human, invoice_path(expense.invoice) %>
              <% else %>
                <%= link_to_edit expense %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>

      <tfoot>
        <th><%= Expense.human_attribute_name(:total) %></th>
        <th></th>
        <th></th>
        <th><%= humanized_money @total_amount %></th>
        <th></th>
        <th></th>
        <th></th>
      </tfoot>
    </table>
    <%= will_paginate @expenses, renderer: BootstrapPagination::Rails %>
  <% else %>
    <p><%= t('shared.no_entities_found', model: Expense.model_name.human(count: 2)) %></p>
  <% end %>
</div>

<div class="actions">
  <% if can? :create, Expense %>
    <%= button_to_new Expense %>
  <% end %>
</div>

app/views/expenses/new.html.erb
<%= page_title_for resource: Expense, action: :new %>

<%= render 'form' %>